# Generated by Django 5.0.14 on 2026-08-15 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('barbers', '0001_initial'),
        ('seats', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='barbers.barber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.customer')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='seats.seat')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='shop.barbershop')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['shop', 'starts_at'], name='queue_appoi_shop_id_9c64f6_idx'), models.Index(fields=['barber', 'starts_at'], name='queue_appoi_barber__097a78_idx'), models.Index(fields=['seat', 'starts_at'], name='queue_appoi_seat_id_a124b0_idx'), models.Index(fields=['status', 'starts_at'], name='queue_appoi_status_2d61e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('SERVING', 'Serving'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='barbers.barber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='accounts.customer')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='seats.seat')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='shop.barbershop')),
            ],
            options={
                'ordering': ['shop', 'queue_number'],
                'indexes': [models.Index(fields=['shop', 'status'], name='queue_queue_shop_id_bb8021_idx'), models.Index(fields=['customer', 'status'], name='queue_queue_custome_87b45a_idx'), models.Index(fields=['barber', 'status'], name='queue_queue_barber__7c1136_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('shop', 'queue_number'), name='unique_queue_number_per_shop'),
        ),
    ]
