# Generated by Django 5.0.14 on 2026-08-15 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='barbers.barber')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='shop.barbershop')),
            ],
            options={
                'ordering': ['shop', 'label'],
                'indexes': [models.Index(fields=['shop', 'status'], name='seats_seat_shop_id_12c655_idx'), models.Index(fields=['barber', 'status'], name='seats_seat_barber__40677d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('shop', 'label'), name='unique_seat_label_per_shop'),
        ),
    ]
