# Generated by Django 5.0.14 on 2026-08-15 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='shop.barbershop')),
            ],
            options={
                'ordering': ['shop', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['shop', 'is_active'], name='barbers_bar_shop_id_f54cc6_idx'), models.Index(fields=['specialty'], name='barbers_bar_special_ecb98c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='barber',
            constraint=models.UniqueConstraint(fields=('shop', 'first_name', 'last_name'), name='unique_barber_name_per_shop'),
        ),
    ]
